### ISSUE TITLE
Greylist.py SQL batch fix needed

### ISSUE THREAD

**Issue by drablo** [vokac/ppolicy#1]
Hi Petr, 

Change the following line in Greylist.py: try:
            sql = "CREATE TABLE IF NOT EXISTS `%s` (`sender` VARCHAR(255) NOT NULL, `recipient` VARCHAR(255) NOT NULL, `client_address` VARCHAR(50), `date` DATETIME, `state` TINYINT DEFAULT 0, INDEX (`sender`), INDEX (`recipient`), INDEX (`client_address`)) %s" % (table, Greylist.DB_ENGINE)

to:

`client_address` VARCHAR(255),

otherwise client addresses longer than 50 characters will never go through the greylist.

Thanks,
Peter S.

**Comment by vokac** [comment]
column size modified in c0e853e560f5b65958a261f97fc7fc360d994579
